version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: local_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.9.3
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/airflow-dags
      AIRFLOW__WEBSERVER__SECRET_KEY: airflow_secret_key_123

    volumes:
      - ../:/opt/airflow/airflow-dags
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    depends_on:
      - airflow-webserver
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/airflow-dags
      AIRFLOW__WEBSERVER__SECRET_KEY: airflow_secret_key_123

    volumes:
      - ../:/opt/airflow/airflow-dags
    command: scheduler

volumes:
  pg_data:
